### ISSUE TITLE
Suggestion: teach flexbox and CSS grid

### ISSUE THREAD

**Issue by missmatsuko** [ladieslearningcode/llc-html-css-multi-page-site#18]
Flexbox and CSS Grid are getting more and more support. I think new learners would benefit from exposure to flexbox and CSS grid. If this is ever going to be incorporated into this workshop, I think the preparation needs to start soon.

**Comment by kasslent** [comment]
Thanks for the recommendation! We are currently making updates, including the incorporation of flexbox.
